name: E2E Cuda

on:
  schedule:
    # Run every day at 23:00 UTC
    - cron: '0 23 * * *'
  workflow_call:

permissions:
  contents: read
  pull-requests: write

jobs:
  e2e-build-hw:
    if: github.repository == 'oneapi-src/unified-runtime'  # run only on upstream; forks will not have the HW
    name: Start e2e job
    # use core flow, run it with cuda specific parameters
    uses: ./.github/workflows/e2e_core.yml
    with:
      name: "CUDA"
      runner_tag: "CUDA_E2E"
      str_name: "cuda"
      prefix: "ext_oneapi_"
      config: "--cuda"
      unit: "gpu"
      trigger: "${{github.event_name}}"
