name: Build and test on Hardware

on: [push, pull_request]

jobs:
  build_intel:
    name: Build - GPU Intel
    strategy:
      matrix:
        build_type: [Debug, Release]
        compiler: [{c: gcc, cxx: g++}, {c: clang, cxx: clang++}]

    runs-on: gpu-intel

    steps:
    - uses: actions/checkout@v3

    - name: Install pip packages
      run: pip install -r third_party/requirements.txt
    
    - name: Download DPC++
      run: |
        wget -O ${{github.workspace}}/dpcpp_compiler.tar.gz https://github.com/intel/llvm/releases/download/sycl-nightly%2F20230626/dpcpp-compiler.tar.gz
        tar -xvf ${{github.workspace}}/dpcpp_compiler.tar.gz

    - name: Configure CMake
      run: >
        cmake
        -B${{github.workspace}}/build
        -DCMAKE_BUILD_TYPE=${{matrix.build_type}}
        -DCMAKE_C_COMPILER=${{matrix.compiler.c}}
        -DCMAKE_CXX_COMPILER=${{matrix.compiler.cxx}}
        -DUR_ENABLE_TRACING=ON
        -DUR_BUILD_TESTS=ON
        -DUR_DEVELOPER_MODE=OFF
        -DUR_FORMAT_CPP_STYLE=OFF
        -DVAL_USE_LIBBACKTRACE_BACKTRACE=OFF
        -DUR_DPCXX=${{github.workspace}}/dpcpp_compiler/bin/clang++

    - name: Build
      run: cmake --build ${{github.workspace}}/build -j $(nproc)

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{matrix.build_type}} --output-on-failure -L "python|umf|loader|validation|tracing|unit|urtrace"
